linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell

linters-settings:
  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
