version: 2

builds:
  - main: ./cmd/ccfg
    binary: ccfg
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^style:"

brews:
  - skip_upload: auto
    repository:
      owner: jeremy-kr
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/jeremy-kr/ccfg
    description: TUI dashboard for viewing Claude Code config files
    license: MIT
    test: |
      system "#{bin}/ccfg", "--version"
    install: |
      bin.install "ccfg"
